# Запускать из папки backend (там же, где alembic.ini), например:
#   cd C:\Users\dmitr\source\Velo-system-v2\velo-system\backend
#   powershell -ExecutionPolicy Bypass -File .\restore_migrations.ps1
#
# Скрипт восстанавливает 2 файла миграций в alembic\versions\

New-Item -ItemType Directory -Force -Path .\alembic\versions | Out-Null

@'
"""initial schema

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-07-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ELECTRO', 'MECHANIC', name='biketype'), nullable=False, comment='Тип велосипеда: электро или механический'),
    sa.Column('owner_type', sa.Enum('VM', 'VITALY', name='bikeownertype'), nullable=True, comment='Кому принадлежит велосипед (арендодатель): ВМ или Виталий'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='VIN / номер рамы — обязательное уникальное поле'),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('READY', 'RENTED', 'REPAIR', 'STOLEN', name='bikestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bikes_serial_number'), 'bikes', ['serial_number'], unique=True)
    op.create_index(op.f('ix_bikes_type'), 'bikes', ['type'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), server_default='2', nullable=False, comment="Минимальный остаток, ниже которого позиция считается 'мало на складе'"),
    sa.Column('purchase_price', sa.Float(), nullable=False, comment='Закупочная стоимость'),
    sa.Column('sale_price', sa.Float(), nullable=False, comment='Цена продажи клиенту'),
    sa.Column('owner', sa.Enum('KIRILL', 'VITALY', name='ownertype'), nullable=False, comment='Принадлежность: Кирилл или Виталий'),
    sa.Column('supplier', sa.String(length=255), nullable=True, comment='Поставщик / источник'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_category'), 'parts', ['category'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'ARCHIVED', name='personstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    op.create_index(op.f('ix_people_phone'), 'people', ['phone'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False, comment='Базовая цена работы без запчастей'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('passport_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('issued_by', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('person_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'tag_id', name='uq_person_tag')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_per_day', sa.Float(), nullable=True, comment='Стоимость аренды в день'),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='rentalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'WAITING_PARTS', 'DONE', 'CANCELLED', name='repairstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True, comment='Сотрудник, закрывший ремонт (обязателен при переводе в статус done)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False, comment='Закупочная стоимость на момент добавления в ремонт'),
    sa.Column('sale_price', sa.Float(), nullable=False, comment='Цена продажи клиенту на момент добавления в ремонт'),
    sa.Column('owner', sa.Enum('KIRILL', 'VITALY', name='ownertype'), nullable=False, comment='Принадлежность запчасти: Кирилл или Виталий'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена за эту услугу в данном ремонте (может отличаться от базовой)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Предустановленные теги клиентов
    for _tag_name in ("Магнит", "Самокат", "Самооплата", "Др. проект"):
        op.execute(
            sa.text(
                "INSERT INTO tags (name, created_at, updated_at) "
                "VALUES (:name, now(), now())"
            ).bindparams(name=_tag_name)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_services')
    op.drop_table('repair_parts')
    op.drop_table('repairs')
    op.drop_table('rentals')
    op.drop_table('photos')
    op.drop_table('person_tags')
    op.drop_table('passport_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('services')
    op.drop_index(op.f('ix_people_phone'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_parts_category'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_bikes_type'), table_name='bikes')
    op.drop_index(op.f('ix_bikes_serial_number'), table_name='bikes')
    op.drop_table('bikes')
    # ### end Alembic commands ###

'@ | Set-Content -Path .\alembic\versions\001_initial_schema.py -Encoding utf8

@'
"""add user role and created_by_user_id

Revision ID: 005_add_roles
Revises: 001_initial_schema
Create Date: 2026-07-05
"""
from alembic import op
import sqlalchemy as sa

revision = "005_add_roles"
down_revision = "001_initial_schema"
branch_labels = None
depends_on = None


user_role_enum = sa.Enum("ADMIN", "MECHANIC", "MANAGER", name="userrole")


def upgrade() -> None:
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default="MECHANIC",
        ),
    )

    # Первый (уже существующий) пользователь должен стать admin —
    # иначе после этой миграции им некому будет управлять системой.
    op.execute("UPDATE users SET role = 'ADMIN' WHERE id = (SELECT MIN(id) FROM users)")

    op.add_column(
        "repairs",
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=True,
            comment="Сотрудник, создавший запись о ремонте",
        ),
    )
    op.create_foreign_key(
        "fk_repairs_created_by_user_id_users",
        "repairs", "users",
        ["created_by_user_id"], ["id"],
    )

    op.add_column(
        "rentals",
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=True,
            comment="Сотрудник, создавший запись об аренде",
        ),
    )
    op.create_foreign_key(
        "fk_rentals_created_by_user_id_users",
        "rentals", "users",
        ["created_by_user_id"], ["id"],
    )


def downgrade() -> None:
    op.drop_constraint("fk_rentals_created_by_user_id_users", "rentals", type_="foreignkey")
    op.drop_column("rentals", "created_by_user_id")

    op.drop_constraint("fk_repairs_created_by_user_id_users", "repairs", type_="foreignkey")
    op.drop_column("repairs", "created_by_user_id")

    op.drop_column("users", "role")
    user_role_enum.drop(op.get_bind(), checkfirst=True)

'@ | Set-Content -Path .\alembic\versions\005_add_roles.py -Encoding utf8

Write-Host "Готово: файлы миграций восстановлены." -ForegroundColor Green
Get-ChildItem .\alembic\versions\
