"""update bike model

Revision ID: 912080c999cb
Revises: 
Create Date: 2026-05-31 15:31:21.663172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912080c999cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('owner_type', sa.Enum('VM', 'VITALY', name='bikeownertype'), nullable=True, comment='Кому принадлежит велосипед (арендодатель): ВМ или Виталий'))
    op.alter_column('bikes', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ELECTRO', 'MECHANIC', name='biketype'),
               comment='Тип велосипеда: электро или механический',
               existing_comment='Электровелосипед, Механический велосипед',
               existing_nullable=False)
    op.drop_constraint(op.f('bikes_owner_person_id_fkey'), 'bikes', type_='foreignkey')
    op.drop_column('bikes', 'owner_person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('owner_person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bikes_owner_person_id_fkey'), 'bikes', 'people', ['owner_person_id'], ['id'])
    op.alter_column('bikes', 'type',
               existing_type=sa.Enum('ELECTRO', 'MECHANIC', name='biketype'),
               type_=sa.VARCHAR(),
               comment='Электровелосипед, Механический велосипед',
               existing_comment='Тип велосипеда: электро или механический',
               existing_nullable=False)
    op.drop_column('bikes', 'owner_type')
    # ### end Alembic commands ###
